### PR TITLE
RU update from Smart-Soft

### PR DESCRIPTION
**Pull request by kekek2**
RU translation updated.

### CODE REVIEW

**Comment by fichtner** [comment]
Something went wrong here, the translated items dropped from 97% to 95%?

**Comment by kekek2** [comment]
Fixed to 99%

**Comment by kekek2** [comment]
In prevision commit was added strings from XML <labels>, but they not translated. I remove temporary they.

**Comment by fichtner** [comment]
I fixed it up further, it's now 100% complete according to our current template. Thanks! :)

Commit: 13c994d81

**Pull request closed without merging**
