### PR TITLE
Update zh_TW.po

### PR DESCRIPTION
**Pull request by marchfun1**
Update zh_TW.po 
About 96% completed.

### CODE REVIEW

**Comment by fichtner** [comment]
Thanks for the submission. This is a large blob so I'd like to know what @jasoncheng7115 thinks since he started the translation and brought it to 56% initially.

**Comment by jasoncheng7115** [comment]
The content of this PR seems to be machine translated, and most of the content terms are not in Taiwanese Traditional Chinese (zh_TW).

Thanks marchfun1, but I personally don't think this translation file is suitable to be merged into the zh_TW translation file.

Thanks @fichtner , I will continue with the translation on the basis of 56%, again using Taiwanese traditional Chinese terminology, not machine translation (because the machine translation will be biased towards the terminology of zh_CN instead of zh_TW).

**Comment by fichtner** [comment]
@jasoncheng7115 ok, closing this one then

**Comment by marchfun1** [comment]
Machine translation!?

I started working on this content half a year ago. and always just used it for myself. I only uploaded it recently when I saw that you  could upload translations. 

I've been in this field for a long time. Microsoft Works, Microsoft VB, Microsoft Internet Explorer, Microsoft FrontPage, Microsoft Publisher, Microsoft Small Business Customer Manager, Microsoft MSDN Web Site, Microsoft HotMail, Microsoft MSN Communities, Kaspersky Anti-virus, etc. All of these zh_TW are my previous translation works. 

It's okay if you don't want to use it. I'm happy as long as I can use it myself."

**Comment by jasoncheng7115** [comment]
I've reviewed most of the content, and I've seen a lot of localized Taiwanese Traditional Chinese phrases and some Simplified Chinese phrases. Since there are a lot of them, I'm guessing that they might be machine translations, sorry if I've offended you.

Due to the sheer volume and content, it looks very much like a machine translation (either Microsoft or Google).
One source of localization terms you can refer to is the previous Microsoft Langugage Portal.

If you want to do a translation into Taiwanese Traditional Chinese, you should use the terminology that is already available in Taiwan.

Since too many terms are not localized to zh_TW, this is the reason I don't recommend incorporating them, for example:

Kernel: It is "核心", but you translate it as "內核".
Certificate: It is "憑證", but you translate it as "證書".
User Certificates: It's "用戶憑證", but you translate it as "使用者驗證".
Archive: It is "壓縮檔", but you translate it as "檔案檔案".
Interface: It is "介面", but you translate it as "端口".
Certificate Authority: It is "憑證簽發", but you translate it as "憑證頒發".
Group Naming Attribute: It is "介面", but you translate it as "端口".
HTTP Header: It is "HTTP 標頭", but you translate it as "HTTP表頭".
Signing Request: It is "簽署請求", but you translate it as "簽名請求".
Mobile Users: It is "行動裝置使用者", but you translate it as "移動使用者".

Due to the large number of incorrect terms, such translations can cause problems for users.

One of the captures:
image

**Comment by fichtner** [comment]
I'm going to back @jasoncheng7115 here for varying reasons, but I also don't want to diminish your work effort, @marchfun1.

We are definitely going to open the translation in Poeditor for multiple contributors yet @jasoncheng7115 already planned to finish it and I want to give him the time to do it. This is also intended as a baseline for further edits that should avoid contention such as this over style and wording/phrasing.


Cheers,
Franco

**Pull request closed without merging**
