### PR TITLE
Update it_IT.po

### PR DESCRIPTION
**Pull request by Antonio-Prado**
fixed some translations and added new. to be continued

### CODE REVIEW

**Comment by fichtner** [comment]
Hi Antonio,

Thanks for this! I will merge this, but if you want to contribute we try to collaborate here instead as pull requests do not work well with multiple translators: https://translate.opnsense.org/

If you want an account simply send a mail to project AT opnsense DOT org

I know it's tempting to fix strings that seem wrong, but in the long run adding new translations to a language that is still in development lets it progress quicker. Translations can always be fixed later. :)


Cheers,
Franco

**Comment by Antonio-Prado** [comment]
hi,

just requested an account
thank you
--
antonio

**Comment by Antonio-Prado** [comment]
@fichtner, sent my request to project AT opnsense DOT org

there is nobody in?
--
antonio

**Comment by fichtner** [comment]
I will answer today, sorry for the delay

**Pull request merged**
