### PR TITLE
I guess this is better Japanese translation of "Prefer IPv4 over IPv6"

### PR DESCRIPTION
**Pull request by nhirokinet**
Hi,

Here is translation of "Prefer IPv4 over IPv6": it is not a technology called "IPv4 over IPv6" which sounds like tunnel, rather this is just preferring IPv4 better than IPv6.

I felt this makes less misunderstanding, how do you think about it?

Or may be it is more simple to write "IPv4 を優先".

If some other Japanese agree, I'm glad if it is merged.

### CODE REVIEW

**Comment by taguchi-ch** [comment]
Hi nhirokinet,

Thanks for your point.
This is simply depending on if the OPNsense team's intent is "Prefer ‘IPv4’ over ‘IPv6’ “ or "Prefer ‘IPv4 over IPv6' ".
Therefore, at first, we should make sure of the original text's meaning to the OPNsense team.
If the former is right, I agree with this fix.

Regards,
Chie Taguchi

**Comment by taguchi-ch** [comment]
Hi nhirokinet,

Japanese translation team consider this problem, and we decide to take it.:)
And you have two way about how to merge this fix.
OPNsense translation project is going on other translation server (https://translate.opnsense.org/projects/), not github’s repo.
Therefore, if you would like to join the project and fix this issue by yourself, you send mail to franco@opnsense.org to receive an account.
Or you do not hope so, I will do this correction on translation server.
Which is your selecion?

Thanks,
Chie Taguchi

**Comment by nhirokinet** [comment]
Hi, taguch-ch,

Thank you for confirmation.

For now, I would prefer if you would make a correction to the translation server. If I find I am likely to do that repeatedly in the future, I will ask for a translator account then.

**Comment by taguchi-ch** [comment]
Hi nhirokinet,

OK.
I will fix it on translation server later.
We appreciate feedback from you and welcome you to join our team someday.

Cheers,
Chie Taguchi

**Comment by taguchi-ch** [comment]
fixed.

**Comment by taguchi-ch** [comment]
Fixed.

Chie Taguchi

**Comment by nhirokinet** [comment]
Thank you!

**Pull request closed without merging**
