### PR TITLE
Update ru_RU.po

### PR DESCRIPTION
**Pull request by f87**
Russian translation edits

### CODE REVIEW

**Comment by AdSchellevis** [comment]
If you want to contribute to the translations, best create an account here https://poeditor.com/join/project/JErIQiUPQa and drop us an email so we can make sure access is properly configured. we don't accept PR's on po files.

**Comment by f87** [comment]
> If you want to contribute to the translations, best create an account here https://poeditor.com/join/project/JErIQiUPQa and drop us an email so we can make sure access is properly configured. we don't accept PR's on po files.

I'm sorry, I registered, but I don't understand what's next?

**Comment by AdSchellevis** [comment]
@f87 we need to allow access,I've just granted you access, you should be able to access Russian now.

**Comment by f87** [comment]
> @f87 we need to allow access,I've just granted you access, you should be able to access Russian now.

Thanks.

**Comment by f87** [comment]
> we need to allow access,I've just granted you access, you should be able to access Russian now.

I understand that POEditor does not have all the data for translation. For example, there are no widgets. Right?

image
image
image

**Comment by fichtner** [comment]
Same question as https://github.com/opnsense/lang/issues/56

It takes time to update the templates to the new source strings and pull them back into the project.

**Comment by f87** [comment]
Okay, I get it, my translation skills are very limited. In" github "you do not accept translations, "POEditor" - outdated templates. If possible, I will edit in the "POEditor", but won't this work be useless to anyone? How often do you get transfers from "POEditor", month, year?

**Comment by AdSchellevis** [comment]
it varies, but we're a bit lagging behind there at the moment. It's quite busy with all the work we'er already doing for OPNsense but we'll definitely put an update on the list of things todo. (and a fetch from poeditor after people had time to translate the differences)

**Pull request closed without merging**
