### PR TITLE
Translate for tabs in .XML

### PR DESCRIPTION
**Pull request by kekek2**
Tabs in proxy configuration don't translated.

### CODE REVIEW

**Comment by fichtner** [comment]
@kekek2 Tab/subtab looks good. Are we sure they are already translated or do they need translation support in core.git for rendering still?

In any case, I will regenerate the template when 17.1 release is built so that we have all of those tabs for later translation as well. :)

Russian update added strings, but also removed some, decreasing overall progress from 4863 to 4764. Was this intended? If not, should I manually merge this or do you want to fix it up?

**Comment by kekek2** [comment]
I have new ru_RU.po. I can't create second pull request, while first is open.

**Comment by fichtner** [comment]
no problem. in the meantime, I applied the tab/subtab fix. thanks!

**Comment by kekek2** [comment]
Fixed translate

**Comment by fichtner** [comment]
Had to redo this so it went in as a manual merge, now at 95% complete. Thanks!

**Pull request closed without merging**
