### PR TITLE
RU update from Smart-Soft

### PR DESCRIPTION
**Pull request by evbevz**
RU translation updated.

### CODE REVIEW

**Comment by fichtner** [comment]
Looks good, thanks! :)

**Comment by evbevz** [comment]
Hi, Franco!

When you plan to update sources and templates in opnsense-lang?
I want to make translation of <label> tags from XML. Labels have to appear now after pull-request #9 https://github.com/opnsense/lang/commit/44aeafe0bbd320bbcad2961e81c6c4f4f1c5fe71 <https://github.com/opnsense/lang/commit/44aeafe0bbd320bbcad2961e81c6c4f4f1c5fe71>
Or I have to do it myself?

Evgeny Bevz.

**Comment by evbevz** [comment]
Hi, Franco!

When you plan to update sources and templates in opnsense-lang?
I want to make translation of <label> tags from XML. Labels have to appear now after pull-request #9 https://github.com/opnsense/lang/commit/44aeafe0bbd320bbcad2961e81c6c4f4f1c5fe71 <https://github.com/opnsense/lang/commit/44aeafe0bbd320bbcad2961e81c6c4f4f1c5fe71>
Or I have to do it myself?

Evgeny.

**Comment by fichtner** [comment]
Hi Evgeny,

Ideally we wouldn't touch the templates for the next 3 months to avoid unnecessary workload and degradation of translations in 16.7.x.

There'd be no point in doing the work manually up front as we have our translation server on the side and all changes should be equally merged.

How long can this wait from your point of view? I'm only asking to see if we can find a fitting timeline that doesn't require us to deal with Pootle every week, which is time-consuming and can lose translations made by other users for all languages.


Cheers,
Franco

**Comment by evbevz** [comment]
OK, let be so. We will wait.

**Comment by fichtner** [comment]
Thanks :) FWIW, there are 3% strings untranslated in the current template that could be picked up in the meantime: https://raw.githubusercontent.com/opnsense/lang/036784e29276e7cae85cfd5076f35963a1f92c13/ru_RU.po

**Pull request merged**
