### PR TITLE
Add extracting labels from XML foms.

### PR DESCRIPTION
**Pull request by kekek2**
collect.py find translable string only from <help></help> in XML forms.

### CODE REVIEW

**Comment by AdSchellevis** [comment]
@kekek2 thank you!

**Comment by fichtner** [comment]
Is this actually translated in the controller/view or does it need support there too?

**Comment by AdSchellevis** [comment]
@fichtner the support seem to be in https://github.com/opnsense/core/blob/master/src/opnsense/mvc/app/controllers/OPNsense/Base/ControllerBase.php#L108

**Comment by fichtner** [comment]
ok, great, thanks :)

**Pull request merged**
